name: ingest-and-cluster
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install feedparser requests simhash sentence-transformers psycopg2-binary pyyaml numpy
      - run: python ingest.py
        env:
          PG_CONN: ${{ secrets.PG_CONN }}
      - run: python cluster.py
        env:
          PG_CONN: ${{ secrets.PG_CONN }}
